Add JWT secret check in CI workflow
Add a step to check for the presence of JWT_SECRET in the workflow.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,6 +5,7 @@ on:
     branches:
       - master
       - develop
+
   pull_request:
     branches:
       - master
@@ -52,6 +53,15 @@ jobs:
 
       - name: Install dependencies
         run: npm ci
+
+      - name: Check JWT secret
+        run: |
+          if [ -z "$JWT_SECRET" ]; then
+            echo "JWT_SECRET is missing"
+            exit 1
+          else
+            echo "JWT_SECRET is available"
+          fi
 
       - name: Build Next.js application
         run: npm run build
